### ISSUE TITLE
PowerShell code in .bat file? 

### ISSUE THREAD

**Issue by bambams** [TheGameFreak720/windows-scripts#1]
Does that even work if invoked?

**Comment by TheGameFreak720** [comment]
Yes, it does

**Comment by TheGameFreak720** [comment]
If you got any errors please open an issue for it

**Comment by bambams** [comment]
```
D:\Users\Brandon\src> cat foo.bat
Write-Host 'Hello, World!'

D:\Users\Brandon\src> foo.bat

Write-Host 'Hello, World!'
'Write-Host' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by TheGameFreak720** [comment]
That is not the same as what the .bat files are doing here. See this guide to set your own .bat files https://www.windowscentral.com/how-create-and-run-batch-file-windows-10

Furthermore for this .bat files to work you need to have to run as administrator in powershell because it changes some internal settings

**Comment by bambams** [comment]
I'm already quite familiar with batch scripting which is why I found this so confusing. I don't think that this will ever work unless you maybe map `.bat` files to the PowerShell interpreter. Ordinarily PowerShell scripts use the `.ps1` extension I think.

**Comment by TheGameFreak720** [comment]
you don't need to map bambams. This command to install chocolatey it's on its doc and worked on my machine just fine. The chocolatey commands can be appended next to each other like any package manager in Linux. If you run with issues running this specific `.bat` files let me know

**Comment by bambams** [comment]
Sorry for the confusion. I'm referring to this script: https://github.com/TheGameFreak720/windows-scripts/blob/master/install-chocolatey.bat.

**Comment by TheGameFreak720** [comment]
Sorry, I haven't had time to check this. I will run the script this weekend and let you know the results

**Comment by TheGameFreak720** [comment]
Just changed the script to be a ps1 and it runs properly granted that you unblock it.
